// Shared mock data for all Cloud Loop pages

export const programs = [
  {
    id: "google-cloud-arcade",
    slug: "google-cloud-arcade",
    name: "GOOGLE CLOUD ARCADE Facilitator Program",
    provider: "Google",
    providerLogo: "https://www.google.com/favicon.ico",
    category: "Cloud",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "13 July 2026 – 14 September 2026",
    deadline: "2026-09-14",
    eligibility: "Students enrolled in any degree program",
    keyBenefit: "Free Google Cloud credits, Arcade Games, Skill Badges, milestone rewards & swag",
    description:
      "The Google Cloud Arcade Facilitator Program is Google's official learning initiative designed for students interested in Cloud Computing, Artificial Intelligence, and Google Cloud technologies. Participants receive free learning resources, Google Cloud credits, Arcade Games, Skill Badges, milestone rewards, and an opportunity to become part of a growing cloud community. The program is completely free to join.",
    tags: ["Cloud", "GCP", "Learning", "Badges", "Facilitator", "AI", "Free"],
    website: "https://rsvp.withgoogle.com/events/arcade-facilitator/",
    registrationForm: "https://forms.gle/Z2TX54F8bQ4ooV5c9",
    facilitatorCode: "GCAF26-IN-MGG-3E2",
    featured: true,
    applicants: 45000,
  },
  {
    id: "mlsa",
    slug: "microsoft-learn-student-ambassadors",
    name: "Microsoft Learn Student Ambassadors",
    provider: "Microsoft",
    providerLogo: "https://www.microsoft.com/favicon.ico",
    category: "Ambassador",
    status: "open" as const,
    difficulty: "Intermediate" as const,
    duration: "Ongoing",
    deadline: "2024-10-15",
    eligibility: "Currently enrolled students at accredited universities",
    keyBenefit: "Azure credits, LinkedIn Premium, free certifications, mentorship",
    description:
      "The Microsoft Learn Student Ambassadors program helps students make an impact in their local communities by hosting events, workshops and hackathons powered by Microsoft technology.",
    tags: ["Azure", "Microsoft", "Community", "Leadership"],
    website: "https://studentambassadors.microsoft.com",
    featured: true,
    applicants: 32000,
  },
  {
    id: "gsoc",
    slug: "google-summer-of-code",
    name: "Google Summer of Code",
    provider: "Google",
    providerLogo: "https://www.google.com/favicon.ico",
    category: "Open Source",
    status: "closed" as const,
    difficulty: "Advanced" as const,
    duration: "12 weeks",
    deadline: "2024-04-02",
    eligibility: "Students 18+ years of age",
    keyBenefit: "Stipend up to $6,600 + mentorship from top OSS contributors",
    description:
      "GSoC is a global program focused on bringing more student developers into open source software development. Students work with an open source organization on a 12-week programming project during their break from school.",
    tags: ["Open Source", "Programming", "Stipend", "Mentorship"],
    website: "https://summerofcode.withgoogle.com",
    featured: true,
    applicants: 18000,
  },
  {
    id: "gssoc",
    slug: "girlscript-summer-of-code",
    name: "GirlScript Summer of Code",
    provider: "GirlScript Foundation",
    providerLogo: "/providers/girlscript.png",
    category: "Open Source",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "3 months",
    deadline: "2024-11-30",
    eligibility: "All students, especially beginners in open source",
    keyBenefit: "Swag, certificates, top performer recognition, job referrals",
    description:
      "GirlScript Summer of Code is an Open Source Program conducted by the GirlScript Foundation that gives students a head-start in open source contributions.",
    tags: ["Open Source", "Beginner Friendly", "Community"],
    website: "https://gssoc.girlscript.tech",
    featured: false,
    applicants: 22000,
  },
  {
    id: "github-campus-expert",
    slug: "github-campus-expert",
    name: "GitHub Campus Expert",
    provider: "GitHub",
    providerLogo: "https://github.com/favicon.ico",
    category: "Ambassador",
    status: "open" as const,
    difficulty: "Intermediate" as const,
    duration: "Ongoing",
    deadline: "2024-09-15",
    eligibility: "Students who are GitHub users and want to lead communities",
    keyBenefit: "Training, swag, GitHub Pro, speaking opportunities, conference travel",
    description:
      "Campus Experts are student leaders that strive to build diverse and inclusive spaces to learn skills, share their experiences, and build projects together.",
    tags: ["GitHub", "Community", "Leadership", "Open Source"],
    website: "https://education.github.com/campus_experts",
    featured: false,
    applicants: 8500,
  },
  {
    id: "aws-educate",
    slug: "aws-educate",
    name: "AWS Educate",
    provider: "Amazon Web Services",
    providerLogo: "https://aws.amazon.com/favicon.ico",
    category: "Cloud",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "Self-paced",
    deadline: "Always open",
    eligibility: "Students 13+ years old",
    keyBenefit: "Free cloud training, badges, job prep resources",
    description:
      "AWS Educate is Amazon's global initiative to provide students and educators with the resources needed to greatly accelerate cloud-related learning, teaching, and innovation.",
    tags: ["AWS", "Cloud", "Free", "Self-paced"],
    website: "https://aws.amazon.com/education/awseducate",
    featured: false,
    applicants: 120000,
  },
  {
    id: "nvidia-dli",
    slug: "nvidia-deep-learning-institute",
    name: "NVIDIA Deep Learning Institute",
    provider: "NVIDIA",
    providerLogo: "https://www.nvidia.com/favicon.ico",
    category: "AI/ML",
    status: "open" as const,
    difficulty: "Intermediate" as const,
    duration: "Self-paced",
    deadline: "Always open",
    eligibility: "Students with basic Python knowledge",
    keyBenefit: "Industry-recognized certificates, GPU-accelerated labs",
    description:
      "NVIDIA DLI offers hands-on training for developers, data scientists, and researchers looking to solve challenging problems with deep learning and accelerated computing.",
    tags: ["AI", "Deep Learning", "GPU", "Certificates"],
    website: "https://www.nvidia.com/en-us/training",
    featured: false,
    applicants: 67000,
  },
  {
    id: "ibm-skillsbuild",
    slug: "ibm-skillsbuild",
    name: "IBM SkillsBuild",
    provider: "IBM",
    providerLogo: "https://www.ibm.com/favicon.ico",
    category: "Technology",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "Self-paced",
    deadline: "Always open",
    eligibility: "All students",
    keyBenefit: "Free digital credentials, career resources, job placement support",
    description:
      "IBM SkillsBuild provides free education programs for students and adult job seekers to help them build in-demand skills and advance their careers in tech.",
    tags: ["IBM", "Free", "Credentials", "Career"],
    website: "https://skillsbuild.org",
    featured: false,
    applicants: 89000,
  },
  {
    id: "google-student-ambassador",
    slug: "google-student-ambassador",
    name: "Google Developer Student Clubs",
    provider: "Google",
    providerLogo: "https://www.google.com/favicon.ico",
    category: "Community",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "Academic year",
    deadline: "2024-08-31",
    eligibility: "Currently enrolled students at colleges/universities",
    keyBenefit: "Training, Google product access, community leadership experience",
    description:
      "Google Developer Student Clubs (GDSC) are university-based community groups for students interested in Google developer technologies. Students from all undergraduate or graduate programs with an interest in growing as a developer are welcome.",
    tags: ["Google", "Community", "Android", "Web"],
    website: "https://developers.google.com/community/gdsc",
    featured: false,
    applicants: 55000,
  },
  {
    id: "oracle-academy",
    slug: "oracle-academy",
    name: "Oracle Academy",
    provider: "Oracle",
    providerLogo: "https://www.oracle.com/favicon.ico",
    category: "Technology",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "Self-paced",
    deadline: "Always open",
    eligibility: "Students enrolled in educational institutions",
    keyBenefit: "Free curriculum, software, cloud access, certifications",
    description:
      "Oracle Academy advances computer science education globally through a range of educational resources, software and cloud access, and supports instructors and institutions.",
    tags: ["Oracle", "Database", "Java", "Cloud"],
    website: "https://academy.oracle.com",
    featured: false,
    applicants: 41000,
  },
  {
    id: "cisco-networking-academy",
    slug: "cisco-networking-academy",
    name: "Cisco Networking Academy",
    provider: "Cisco",
    providerLogo: "https://www.cisco.com/favicon.ico",
    category: "Networking",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "Self-paced",
    deadline: "Always open",
    eligibility: "All students",
    keyBenefit: "Free networking courses, industry certifications, career pathways",
    description:
      "Cisco Networking Academy is a global IT and cybersecurity education program that partners with learning institutions around the world to empower all people with career opportunities.",
    tags: ["Networking", "Cybersecurity", "Cisco", "CCNA"],
    website: "https://www.netacad.com",
    featured: false,
    applicants: 210000,
  },
  {
    id: "intel-ai-academy",
    slug: "intel-ai-for-youth",
    name: "Intel AI for Youth",
    provider: "Intel",
    providerLogo: "https://www.intel.com/favicon.ico",
    category: "AI/ML",
    status: "open" as const,
    difficulty: "Beginner" as const,
    duration: "6 months",
    deadline: "2024-10-01",
    eligibility: "Students aged 14–22",
    keyBenefit: "AI curriculum, mentorship, hackathon participation, certificate",
    description:
      "Intel AI for Youth is a program that helps students build AI skills, explore career pathways in AI, and create meaningful AI projects for positive social impact.",
    tags: ["AI", "Intel", "Youth", "Mentorship"],
    website: "https://www.intel.com/aiforyouth",
    featured: false,
    applicants: 15000,
  },
];

export const events = [
  {
    id: "1",
    slug: "smart-india-hackathon-2024",
    title: "Smart India Hackathon 2024",
    organizer: "Ministry of Education, Government of India",
    type: "Hackathon",
    date: "2024-12-11",
    endDate: "2024-12-12",
    location: "Multiple Centers across India",
    isOnline: false,
    banner: "/events/sih-2024.jpg",
    registrationDeadline: "2024-10-15",
    description: "SIH 2024 is a national-level hackathon providing students a platform to solve some of the pressing problems we face in our daily lives, and thus inculcate a culture of product innovation and a mindset of problem-solving.",
    prize: "₹1,00,000 per team",
    tags: ["Hackathon", "National", "Government", "Innovation"],
    registered: 12000,
  },
  {
    id: "2",
    slug: "google-hashcode-2024",
    title: "Google Hash Code 2024",
    organizer: "Google",
    type: "Competition",
    date: "2024-11-14",
    endDate: "2024-11-14",
    location: "Online",
    isOnline: true,
    banner: "/events/hashcode.jpg",
    registrationDeadline: "2024-11-01",
    description: "Hash Code is a team programming competition for students and professionals organized by Google. You pick your team and programming language and we give you a problem from Google's real engineering challenges.",
    prize: "Google swag + certificate + internship opportunities",
    tags: ["Competitive Programming", "Google", "Online"],
    registered: 45000,
  },
  {
    id: "3",
    slug: "microsoft-imagine-cup-2024",
    title: "Microsoft Imagine Cup 2024",
    organizer: "Microsoft",
    type: "Competition",
    date: "2024-11-30",
    endDate: "2024-12-01",
    location: "Online + Finals in Seattle",
    isOnline: true,
    banner: "/events/imagine-cup.jpg",
    registrationDeadline: "2024-10-31",
    description: "Imagine Cup is Microsoft's premier student technology competition. Build an AI-powered app using Microsoft Azure and compete with students from around the world.",
    prize: "$100,000 + mentorship + Azure credits",
    tags: ["Azure", "AI", "Microsoft", "Global"],
    registered: 8500,
  },
  {
    id: "4",
    slug: "mlh-hackathon-season",
    title: "MLH Global Hackathon Season",
    organizer: "Major League Hacking",
    type: "Hackathon",
    date: "2024-09-01",
    endDate: "2025-05-31",
    location: "Worldwide (online + in-person)",
    isOnline: true,
    banner: "/events/mlh.jpg",
    registrationDeadline: "Ongoing",
    description: "MLH is the global student developer community. Join hundreds of hackathons throughout the season, build amazing projects, and win prizes.",
    prize: "Varies per hackathon",
    tags: ["Hackathon", "Global", "Student", "MLH"],
    registered: 92000,
  },
  {
    id: "5",
    slug: "aws-builders-fair",
    title: "AWS re:Invent Student Program 2024",
    organizer: "Amazon Web Services",
    type: "Conference",
    date: "2024-12-02",
    endDate: "2024-12-06",
    location: "Las Vegas, Nevada",
    isOnline: false,
    banner: "/events/reinvent.jpg",
    registrationDeadline: "2024-10-15",
    description: "AWS re:Invent student program offers students access to sessions, workshops, and networking events at the world's largest cloud computing conference.",
    prize: "Travel grant + conference pass",
    tags: ["AWS", "Cloud", "Conference", "Networking"],
    registered: 2200,
  },
  {
    id: "6",
    slug: "web3-builders-bootcamp",
    title: "Web3 Builders Bootcamp",
    organizer: "Ethereum Foundation",
    type: "Bootcamp",
    date: "2024-10-14",
    endDate: "2024-10-18",
    location: "Online",
    isOnline: true,
    banner: "/events/web3.jpg",
    registrationDeadline: "2024-10-07",
    description: "A 5-day intensive bootcamp for students to learn Solidity, smart contracts, and build their first dApps with guidance from senior Web3 engineers.",
    prize: "Certificate + Project showcase",
    tags: ["Web3", "Blockchain", "Ethereum", "Bootcamp"],
    registered: 3400,
  },
];

export const internships = [
  // Sorted alphabetically by company name
  {
    id: "adsparkx-ai-intern",
    slug: "adsparkx-ai-intern",
    company: "ADSPARKX Media",
    companyLogo: "https://www.google.com/favicon.ico",
    role: "AI Intern",
    location: "Not Specified",
    locationType: "remote" as const,
    stipend: "Not Disclosed",
    duration: "Internship",
    isPaid: false,
    deadline: "2026-09-30",
    skills: ["AI", "Machine Learning"],
    description: "AI Intern at ADSPARKX Media. Eligible batch: 2025, 2026.",
    tags: ["AI", "Internship", "2025", "2026"],
    applyUrl: "https://adsparkxmedia.keka.com/careers/jobdetails/129430",
    eligibleBatch: "2025, 2026",
    isNew: true,
  },
  {
    id: "emo-energy-dev-intern",
    slug: "emo-energy-dev-intern",
    company: "EMO.energy",
    companyLogo: "https://www.google.com/favicon.ico",
    role: "Software Developer Intern",
    location: "Not Specified",
    locationType: "remote" as const,
    stipend: "₹3–6 LPA",
    duration: "Internship",
    isPaid: true,
    deadline: "2026-09-30",
    skills: ["Software Development"],
    description: "Software Developer Intern at EMO.energy. Stipend: ₹3–6 LPA.",
    tags: ["Software", "Internship"],
    applyUrl: "https://www.linkedin.com/jobs/view/4437015391",
    isNew: true,
  },
  {
    id: "finacplus-frontend-intern",
    slug: "finacplus-frontend-intern",
    company: "FinacPlus",
    companyLogo: "https://www.google.com/favicon.ico",
    role: "Frontend Intern",
    location: "Not Specified",
    locationType: "remote" as const,
    stipend: "Not Disclosed",
    duration: "Internship",
    isPaid: false,
    deadline: "2026-09-30",
    skills: ["Frontend", "React", "JavaScript"],
    description: "Frontend Intern at FinacPlus. Eligible batch: 2025, 2026.",
    tags: ["Frontend", "Internship", "2025", "2026"],
    applyUrl: "https://www.linkedin.com/jobs/view/4438305566/",
    eligibleBatch: "2025, 2026",
    isNew: true,
  },
  {
    id: "ge-healthcare-data-analyst-intern",
    slug: "ge-healthcare-data-analyst-intern",
    company: "GE HealthCare",
    companyLogo: "https://www.gehealthcare.com/favicon.ico",
    role: "Intern - Data Analyst",
    location: "Bengaluru",
    locationType: "onsite" as const,
    stipend: "Not Disclosed",
    duration: "Internship",
    isPaid: false,
    deadline: "2026-09-30",
    skills: ["Data Analysis", "SQL", "Python"],
    description: "Data Analyst Intern at GE HealthCare. Bachelor's / Master's Degree. Freshers welcome.",
    tags: ["Data", "Internship", "Freshers"],
    applyUrl: "https://careers.gehealthcare.com/global/en/job/R4039484/Intern-Data-Analyst",
    isNew: true,
  },
  {
    id: "ge-healthcare-intern",
    slug: "ge-healthcare-intern",
    company: "GE HealthCare",
    companyLogo: "https://www.gehealthcare.com/favicon.ico",
    role: "Intern",
    location: "Not Specified",
    locationType: "hybrid" as const,
    stipend: "Not Disclosed",
    duration: "Internship",
    isPaid: false,
    deadline: "2026-09-30",
    skills: ["Engineering", "Technology"],
    description: "Intern at GE HealthCare. Eligible batch: 2025, 2026.",
    tags: ["Internship", "2025", "2026"],
    applyUrl: "https://careers.gehealthcare.com/global/en/job/GEVGHLGLOBALR4043319EXTERNALENGLOBAL/Intern",
    eligibleBatch: "2025, 2026",
    isNew: true,
  },
  {
    id: "icertis-dev-intern",
    slug: "icertis-dev-intern",
    company: "Icertis",
    companyLogo: "https://www.icertis.com/favicon.ico",
    role: "Development Intern",
    location: "Not Specified",
    locationType: "hybrid" as const,
    stipend: "Not Disclosed",
    duration: "Internship",
    isPaid: false,
    deadline: "2026-09-30",
    skills: ["Software Development", "Programming"],
    description: "Development Intern at Icertis. Eligible batch: 2025, 2026.",
    tags: ["Development", "Internship", "2025", "2026"],
    applyUrl: "https://iaaviz.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/Jobs-at-Icertis/job/7561",
    eligibleBatch: "2025, 2026",
    isNew: true,
  },
  {
    id: "riverhead-backend-intern",
    slug: "riverhead-backend-intern",
    company: "Riverhead",
    companyLogo: "https://www.google.com/favicon.ico",
    role: "Backend Engineer Intern",
    location: "Gurugram",
    locationType: "onsite" as const,
    stipend: "Not Disclosed",
    duration: "Internship",
    isPaid: false,
    deadline: "2026-09-30",
    skills: ["Backend", "Node.js", "API"],
    description: "Backend Engineer Intern at Riverhead. Eligible batch: 2025, 2026.",
    tags: ["Backend", "Internship", "2025", "2026"],
    applyUrl: "https://www.linkedin.com/jobs/view/4436089989/",
    eligibleBatch: "2025, 2026",
    isNew: true,
  },
  {
    id: "stripe-swe-intern",
    slug: "stripe-swe-intern",
    company: "Stripe",
    companyLogo: "https://stripe.com/favicon.ico",
    role: "Software Engineer Intern",
    location: "Not Specified",
    locationType: "hybrid" as const,
    stipend: "₹1 Lakh/month",
    duration: "Internship",
    isPaid: true,
    deadline: "2026-09-30",
    skills: ["Software Engineering", "Programming", "Distributed Systems"],
    description: "Software Engineer Intern at Stripe. Eligible batch: 2026, 2027. Stipend: ₹1 Lakh per month.",
    tags: ["Software", "Paid", "2026", "2027"],
    applyUrl: "https://stripe.com/jobs/listing/software-engineer-intern/8031833",
    eligibleBatch: "2026, 2027",
    isNew: true,
  },
];

export const jobs = [
  // Sorted alphabetically by company name
  {
    id: "adobe-sde",
    slug: "adobe-sde",
    company: "Adobe",
    companyLogo: "https://www.adobe.com/favicon.ico",
    role: "Software Development Engineer",
    location: "Bangalore / Noida",
    locationType: "hybrid" as const,
    salaryRange: "Not Disclosed",
    experience: "Freshers / Experienced",
    category: "Software",
    skills: ["Software Engineering", "Java", "C++"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Software Development Engineer at Adobe. Bachelor's / Master's Degree. Freshers and Experienced welcome.",
    tags: ["Full-time", "Open"],
    applyUrl: "https://careers.adobe.com/us/en/job/R170273/Software-Development-Engineer",
    isNew: true,
  },
  {
    id: "amex-analyst",
    slug: "amex-analyst",
    company: "American Express",
    companyLogo: "https://www.americanexpress.com/favicon.ico",
    role: "Analyst",
    location: "Gurugram",
    locationType: "onsite" as const,
    salaryRange: "Not Disclosed",
    experience: "1–2 Years",
    category: "Data",
    skills: ["Analysis", "Excel", "Python"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Analyst role at American Express, Gurugram. 1–2 years of experience required.",
    tags: ["Full-time", "Finance", "Open"],
    applyUrl: "https://egug.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/26010841",
    isNew: true,
  },
  {
    id: "apna-product-analyst",
    slug: "apna-product-analyst",
    company: "Apna",
    companyLogo: "https://www.apna.co/favicon.ico",
    role: "Product Analyst",
    location: "Bangalore",
    locationType: "hybrid" as const,
    salaryRange: "Not Disclosed",
    experience: "1 Year",
    category: "Data",
    skills: ["Product Analysis", "SQL", "Python", "Analytics"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Product Analyst at Apna, Bangalore. 1 year of experience required.",
    tags: ["Full-time", "Startup", "Open"],
    applyUrl: "https://www.linkedin.com/jobs/view/4440015577/",
    isNew: true,
  },
  {
    id: "cloudflare-systems-engineer",
    slug: "cloudflare-systems-engineer",
    company: "Cloudflare",
    companyLogo: "https://www.cloudflare.com/favicon.ico",
    role: "Systems Engineer",
    location: "Bangalore",
    locationType: "hybrid" as const,
    salaryRange: "Not Disclosed",
    experience: "Not Specified",
    category: "Software",
    skills: ["Systems Engineering", "Networking", "Rust", "Go"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Systems Engineer at Cloudflare, Bangalore.",
    tags: ["Full-time", "Open"],
    applyUrl: "https://job-boards.greenhouse.io/cloudflare/jobs/8022909?gh_jid=8022909",
    isNew: true,
  },
  {
    id: "cognizant-trainee",
    slug: "cognizant-trainee",
    company: "Cognizant",
    companyLogo: "https://www.cognizant.com/favicon.ico",
    role: "Trainee",
    location: "Bangalore (Hybrid)",
    locationType: "hybrid" as const,
    salaryRange: "Not Disclosed",
    experience: "Freshers",
    category: "Software",
    skills: ["Programming", "Problem Solving"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Trainee at Cognizant, Bangalore. Bachelor's / Master's Degree. Freshers welcome.",
    tags: ["Full-time", "Freshers", "Open"],
    applyUrl: "https://careers.cognizant.com/india-en/jobs/00069445301/trainee/",
    isNew: true,
  },
  {
    id: "conga-ai-engineer",
    slug: "conga-ai-engineer",
    company: "Conga",
    companyLogo: "https://www.conga.com/favicon.ico",
    role: "Software Engineer, AI",
    location: "Not Specified",
    locationType: "remote" as const,
    salaryRange: "₹12–15 LPA",
    experience: "2+ Years",
    category: "AI/ML",
    skills: ["AI", "Machine Learning", "Python"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Software Engineer, AI at Conga. 2+ years of experience. Salary: ₹12–15 LPA.",
    tags: ["Full-time", "AI", "Open"],
    applyUrl: "https://www.linkedin.com/jobs/view/4429097877",
    isNew: true,
  },
  {
    id: "digantara-sde1",
    slug: "digantara-sde1",
    company: "Digantara",
    companyLogo: "https://www.digantara.com/favicon.ico",
    role: "SDE I (Data Platform)",
    location: "Not Specified",
    locationType: "hybrid" as const,
    salaryRange: "Not Disclosed",
    experience: "2024, 2025 Batch",
    category: "Software",
    skills: ["Data Platform", "Python", "SQL", "Spark"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "SDE I (Data Platform) at Digantara. Eligible batch: 2024, 2025.",
    tags: ["Full-time", "Space Tech", "Open"],
    applyUrl: "https://careers.kula.ai/digantara/51285?source=jobfound.org",
    eligibleBatch: "2024, 2025",
    isNew: true,
  },
  {
    id: "elevenlabs-fde",
    slug: "elevenlabs-fde",
    company: "ElevenLabs",
    companyLogo: "https://elevenlabs.io/favicon.ico",
    role: "Forward Deployed Engineer (Software Engineer)",
    location: "Remote (Worldwide)",
    locationType: "remote" as const,
    salaryRange: "Not Disclosed",
    experience: "Not Specified",
    category: "Software",
    skills: ["Software Engineering", "Python", "AI"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Forward Deployed Engineer (Software Engineer) at ElevenLabs. Remote worldwide.",
    tags: ["Full-time", "Remote", "AI", "Open"],
    applyUrl: "https://jobs.ashbyhq.com/elevenlabs/6c4c57c1-ec72-42ba-af3a-eb7aebbde2e6",
    isNew: true,
  },
  {
    id: "eurofins-it-engineer",
    slug: "eurofins-it-engineer",
    company: "Eurofins",
    companyLogo: "https://www.eurofins.com/favicon.ico",
    role: "IT Software Engineer",
    location: "Bangalore",
    locationType: "onsite" as const,
    salaryRange: "Not Disclosed",
    experience: "2023, 2024, 2025 Batch",
    category: "Software",
    skills: ["Software Engineering", "Java", "Python"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "IT Software Engineer at Eurofins, Bangalore. Eligible batch: 2023, 2024, 2025.",
    tags: ["Full-time", "Open"],
    applyUrl: "https://jobs.smartrecruiters.com/Eurofins/744000136190299-it-software-engineer?trid=2d92f286-613b-4daf-9dfa-6340ffbecf73&source=jobfound.org",
    eligibleBatch: "2023, 2024, 2025",
    isNew: true,
  },
  {
    id: "forbes-advisor-ase",
    slug: "forbes-advisor-ase",
    company: "Forbes Advisor",
    companyLogo: "https://www.forbes.com/favicon.ico",
    role: "Associate Software Engineer",
    location: "Not Specified",
    locationType: "remote" as const,
    salaryRange: "Not Disclosed",
    experience: "2022–2025 Batch",
    category: "Software",
    skills: ["Software Engineering", "JavaScript", "React"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Associate Software Engineer at Forbes Advisor. Eligible batch: 2022, 2023, 2024, 2025.",
    tags: ["Full-time", "Open"],
    applyUrl: "https://ats.rippling.com/en-GB/forbes-advisor/jobs/9ab58117-0205-4448-b378-f37394d6239a",
    eligibleBatch: "2022, 2023, 2024, 2025",
    isNew: true,
  },
  {
    id: "johnson-controls-get",
    slug: "johnson-controls-get",
    company: "Johnson Controls",
    companyLogo: "https://www.johnsoncontrols.com/favicon.ico",
    role: "Graduate Engineer Trainee",
    location: "Pune",
    locationType: "onsite" as const,
    salaryRange: "Not Disclosed",
    experience: "Freshers / Experienced",
    category: "Software",
    skills: ["Engineering", "Technology"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Graduate Engineer Trainee at Johnson Controls, Pune. Bachelor's / Master's Degree.",
    tags: ["Full-time", "Freshers", "Open"],
    applyUrl: "https://jobs.johnsoncontrols.com/job/WD30274019",
    isNew: true,
  },
  {
    id: "netomi-sde-frontend",
    slug: "netomi-sde-frontend",
    company: "Netomi",
    companyLogo: "https://www.netomi.com/favicon.ico",
    role: "SDE I - Frontend",
    location: "Not Specified",
    locationType: "remote" as const,
    salaryRange: "₹15–20 LPA",
    experience: "1–3 Years",
    category: "Frontend",
    skills: ["React", "TypeScript", "JavaScript", "Frontend"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "SDE I - Frontend at Netomi. 1–3 years of experience. Salary: ₹15–20 LPA.",
    tags: ["Full-time", "Frontend", "Open"],
    applyUrl: "https://jobs.lever.co/netomi/cdeaeaff-68e0-4889-8bb6-a3b5e4a0819b",
    isNew: true,
  },
  {
    id: "oracle-systems-analyst",
    slug: "oracle-systems-analyst",
    company: "Oracle",
    companyLogo: "https://www.oracle.com/favicon.ico",
    role: "Systems Analyst 1",
    location: "Bengaluru",
    locationType: "onsite" as const,
    salaryRange: "Not Disclosed",
    experience: "0–2 Years",
    category: "Software",
    skills: ["Systems Analysis", "SQL", "Java"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Systems Analyst 1 at Oracle, Bengaluru. 0–2 years of experience.",
    tags: ["Full-time", "Freshers", "Open"],
    applyUrl: "https://careers.oracle.com/en/sites/jobsearch/job/319150/",
    isNew: true,
  },
  {
    id: "sifive-engineer1",
    slug: "sifive-engineer1",
    company: "SiFive",
    companyLogo: "https://www.sifive.com/favicon.ico",
    role: "Engineer 1",
    location: "Hyderabad",
    locationType: "onsite" as const,
    salaryRange: "Not Disclosed",
    experience: "2023–2025 Batch",
    category: "Software",
    skills: ["RISC-V", "Hardware Design", "C++"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Engineer 1 at SiFive, Hyderabad. Eligible batch: 2023, 2024, 2025.",
    tags: ["Full-time", "Open"],
    applyUrl: "https://sifive.wd1.myworkdayjobs.com/sifivecareers/job/Hyderabad-India/Engijneer-1_R-101364",
    eligibleBatch: "2023, 2024, 2025",
    isNew: true,
  },
  {
    id: "unreconciled-react-dev",
    slug: "unreconciled-react-dev",
    company: "Unreconciled",
    companyLogo: "https://www.google.com/favicon.ico",
    role: "React Developer",
    location: "Not Specified",
    locationType: "remote" as const,
    salaryRange: "Not Disclosed",
    experience: "2022–2024 Batch",
    category: "Frontend",
    skills: ["React", "JavaScript", "TypeScript"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "React Developer at Unreconciled. Eligible batch: 2022, 2023, 2024.",
    tags: ["Full-time", "Frontend", "Open"],
    applyUrl: "https://www.linkedin.com/jobs/view/4440096468/",
    eligibleBatch: "2022, 2023, 2024",
    isNew: true,
  },
  {
    id: "vymo-devops",
    slug: "vymo-devops",
    company: "Vymo",
    companyLogo: "https://www.getvymo.com/favicon.ico",
    role: "DevOps Engineer",
    location: "Not Specified",
    locationType: "hybrid" as const,
    salaryRange: "Not Disclosed",
    experience: "2025, 2026 Batch",
    category: "DevOps",
    skills: ["DevOps", "Kubernetes", "Docker", "CI/CD"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "DevOps Engineer at Vymo. Eligible batch: 2025, 2026.",
    tags: ["Full-time", "DevOps", "Open"],
    applyUrl: "https://www.linkedin.com/jobs/view/4439451021/",
    eligibleBatch: "2025, 2026",
    isNew: true,
  },
  {
    id: "wells-fargo-swe",
    slug: "wells-fargo-swe",
    company: "Wells Fargo",
    companyLogo: "https://www.wellsfargo.com/favicon.ico",
    role: "Software Engineer",
    location: "Not Specified",
    locationType: "hybrid" as const,
    salaryRange: "₹20–60 LPA",
    experience: "2+ Years",
    category: "Software",
    skills: ["Software Engineering", "Java", "Python", "System Design"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Software Engineer at Wells Fargo. 2+ years of experience. Salary: ₹20–60 LPA.",
    tags: ["Full-time", "Finance", "Open"],
    applyUrl: "https://www.wellsfargojobs.com/en/jobs/r-541334/software-engineer",
    isNew: true,
  },
  {
    id: "zerodha-frontend-engineer",
    slug: "zerodha-frontend-engineer",
    company: "Zerodha Fund House",
    companyLogo: "https://zerodha.com/favicon.ico",
    role: "Frontend Development Engineer",
    location: "Not Specified",
    locationType: "hybrid" as const,
    salaryRange: "Not Disclosed",
    experience: "2021–2024 Batch",
    category: "Frontend",
    skills: ["Frontend", "React", "JavaScript", "TypeScript"],
    isEasyApply: false,
    deadline: "2026-09-30",
    posted: "2026-07-15",
    description: "Frontend Development Engineer at Zerodha Fund House. Eligible batch: 2021, 2022, 2023, 2024.",
    tags: ["Full-time", "Fintech", "Open"],
    applyUrl: "https://careers.zerodhafundhouse.com/jobs/vDiDSpSck6KO/frontend-development-engineer?ft_source=5000608205&ft_medium=5000543982",
    eligibleBatch: "2021, 2022, 2023, 2024",
    isNew: true,
  },
];

export const certifications = [
  {
    id: "1",
    slug: "google-cloud-professional",
    name: "Google Cloud Professional Data Engineer",
    provider: "Google Cloud",
    providerLogo: "https://www.google.com/favicon.ico",
    difficulty: "Professional" as const,
    duration: "3–6 months prep",
    cost: "Paid" as const,
    price: "$200",
    skills: ["BigQuery", "Dataflow", "Pub/Sub", "ML on GCP"],
    description: "Demonstrate your ability to design, build, and operationalize data processing systems on Google Cloud.",
    enrollUrl: "https://cloud.google.com/certification/data-engineer",
    certificatePreview: "/certs/gcp-data-engineer.png",
    rating: 4.7,
    enrolled: 120000,
  },
  {
    id: "2",
    slug: "aws-solutions-architect",
    name: "AWS Certified Solutions Architect – Associate",
    provider: "Amazon Web Services",
    providerLogo: "https://aws.amazon.com/favicon.ico",
    difficulty: "Associate" as const,
    duration: "2–3 months prep",
    cost: "Paid" as const,
    price: "$150",
    skills: ["EC2", "S3", "RDS", "VPC", "CloudFormation"],
    description: "Validate your expertise in designing distributed systems on AWS. The most popular cloud certification worldwide.",
    enrollUrl: "https://aws.amazon.com/certification/certified-solutions-architect-associate",
    certificatePreview: "/certs/aws-saa.png",
    rating: 4.8,
    enrolled: 280000,
  },
  {
    id: "3",
    slug: "meta-frontend-developer",
    name: "Meta Front-End Developer Professional Certificate",
    provider: "Meta (via Coursera)",
    providerLogo: "https://www.meta.com/favicon.ico",
    difficulty: "Beginner" as const,
    duration: "7 months",
    cost: "Paid" as const,
    price: "$49/month",
    skills: ["HTML", "CSS", "JavaScript", "React", "Bootstrap"],
    description: "Launch your career as a front-end developer. Build a portfolio with real-world projects and earn a certificate from Meta.",
    enrollUrl: "https://www.coursera.org/professional-certificates/meta-front-end-developer",
    certificatePreview: "/certs/meta-frontend.png",
    rating: 4.6,
    enrolled: 195000,
  },
  {
    id: "4",
    slug: "microsoft-azure-fundamentals",
    name: "Microsoft Azure Fundamentals (AZ-900)",
    provider: "Microsoft",
    providerLogo: "https://www.microsoft.com/favicon.ico",
    difficulty: "Beginner" as const,
    duration: "1 month prep",
    cost: "Paid" as const,
    price: "$165",
    skills: ["Azure Basics", "Cloud Concepts", "Security", "Pricing"],
    description: "Prove your foundational knowledge of cloud services and how those services are provided with Microsoft Azure.",
    enrollUrl: "https://learn.microsoft.com/en-us/certifications/azure-fundamentals",
    certificatePreview: "/certs/az900.png",
    rating: 4.5,
    enrolled: 340000,
  },
  {
    id: "5",
    slug: "ibm-data-science",
    name: "IBM Data Science Professional Certificate",
    provider: "IBM (via Coursera)",
    providerLogo: "https://www.ibm.com/favicon.ico",
    difficulty: "Beginner" as const,
    duration: "3 months",
    cost: "Free" as const,
    price: "Free to audit",
    skills: ["Python", "SQL", "Data Analysis", "Machine Learning", "Jupyter"],
    description: "Kickstart your career in data science & ML. Build data science skills, learn tools used by industry professionals, and earn a certificate from IBM.",
    enrollUrl: "https://www.coursera.org/professional-certificates/ibm-data-science",
    certificatePreview: "/certs/ibm-ds.png",
    rating: 4.6,
    enrolled: 550000,
  },
  {
    id: "6",
    slug: "deep-learning-specialization",
    name: "Deep Learning Specialization",
    provider: "DeepLearning.AI (via Coursera)",
    providerLogo: "/providers/deeplearning.png",
    difficulty: "Intermediate" as const,
    duration: "4 months",
    cost: "Paid" as const,
    price: "$49/month",
    skills: ["Neural Networks", "CNN", "RNN", "TensorFlow", "Hyperparameter Tuning"],
    description: "The #1 AI course in the world, taught by AI pioneer Andrew Ng. Build and train neural networks, improve ML with best practices.",
    enrollUrl: "https://www.coursera.org/specializations/deep-learning",
    certificatePreview: "/certs/dl-spec.png",
    rating: 4.9,
    enrolled: 780000,
  },
  {
    id: "7",
    slug: "google-ux-design",
    name: "Google UX Design Professional Certificate",
    provider: "Google (via Coursera)",
    providerLogo: "https://www.google.com/favicon.ico",
    difficulty: "Beginner" as const,
    duration: "6 months",
    cost: "Paid" as const,
    price: "$49/month",
    skills: ["UX Research", "Wireframing", "Figma", "Prototyping", "Usability"],
    description: "Get on the fast track to a career in UX design with a professional certificate from Google. No experience or degree required.",
    enrollUrl: "https://www.coursera.org/professional-certificates/google-ux-design",
    certificatePreview: "/certs/google-ux.png",
    rating: 4.8,
    enrolled: 320000,
  },
  {
    id: "8",
    slug: "cisco-ccna",
    name: "CCNA: Cisco Certified Network Associate",
    provider: "Cisco",
    providerLogo: "https://www.cisco.com/favicon.ico",
    difficulty: "Associate" as const,
    duration: "3–4 months prep",
    cost: "Paid" as const,
    price: "$330",
    skills: ["Networking Fundamentals", "IP Services", "Security", "Automation"],
    description: "Validate your skills in network fundamentals, network access, IP connectivity, and more. The most recognized networking certification.",
    enrollUrl: "https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html",
    certificatePreview: "/certs/ccna.png",
    rating: 4.7,
    enrolled: 240000,
  },
];

export const successStories = [
  {
    id: "1",
    name: "Arjun Sharma",
    role: "SDE at Google",
    university: "IIT Bombay, 2024",
    avatar: "/testimonials/arjun.jpg",
    quote:
      "Cloud Loop helped me discover Google Cloud Arcade in my 2nd year. I earned 50+ badges, got shortlisted for STEP internship, and finally landed at Google full-time. I wouldn't have known about half these programs without this platform.",
    program: "Google Cloud Arcade → STEP Intern → Google FTE",
  },
  {
    id: "2",
    name: "Priya Nair",
    role: "ML Engineer at Microsoft",
    university: "NIT Trichy, 2024",
    avatar: "/testimonials/priya.jpg",
    quote:
      "I stumbled upon the MLSA program on Cloud Loop during my 3rd year. The Azure credits and certification pathways gave me a huge edge. Within a year, I had 4 Microsoft certifications and a full-time offer from the Azure team.",
    program: "MLSA → Azure Certifications → Microsoft FTE",
  },
  {
    id: "3",
    name: "Karthik Menon",
    role: "Open Source Engineer at Red Hat",
    university: "BITS Pilani, 2023",
    avatar: "/testimonials/karthik.jpg",
    quote:
      "I used Cloud Loop to plan my entire open source journey — GSoC, GSSoC, GitHub Campus Expert. Cloud Loop showed me what programs were available and when to apply. Best discovery resource for CS students in India.",
    program: "GSSoC → GitHub Campus Expert → GSoC → Red Hat FTE",
  },
];

export const categories = [
  { id: "programs", name: "Programs", icon: "Award", count: 120, description: "Ambassador & learning programs", color: "#4FD9FF" },
  { id: "events", name: "Events", icon: "Calendar", count: 340, description: "Hackathons, workshops & conferences", color: "#7A5CFF" },
  { id: "internships", name: "Internships", icon: "Briefcase", count: 890, description: "Paid & unpaid internship roles", color: "#A855F7" },
  { id: "jobs", name: "Jobs", icon: "Building2", count: 2400, description: "Full-time campus & fresher jobs", color: "#4FD9FF" },
  { id: "certifications", name: "Certifications", icon: "BadgeCheck", count: 560, description: "Industry-recognized certificates", color: "#7A5CFF" },
  { id: "scholarships", name: "Scholarships", icon: "GraduationCap", count: 180, description: "Funding for education", color: "#A855F7" },
  { id: "research", name: "Research", icon: "FlaskConical", count: 95, description: "Research internships & fellowships", color: "#4FD9FF" },
  { id: "community", name: "Community", icon: "Users", count: 60, description: "Student communities & clubs", color: "#7A5CFF" },
];

export const faqs = [
  {
    q: "Is Cloud Loop free to use?",
    a: "Yes, Cloud Loop is completely free for students. We aggregate and curate the best opportunities so you don't have to spend hours across dozens of websites.",
  },
  {
    q: "How often is the content updated?",
    a: "Our team reviews and updates listings daily. We track deadlines, open/close status, and new programs from major tech companies and organizations.",
  },
  {
    q: "Do I need to create an account to browse?",
    a: "No — you can explore all programs, events, jobs, and certifications without an account. An account lets you save opportunities, set deadline reminders, and track applications.",
  },
  {
    q: "Can I submit a program or opportunity that's not listed?",
    a: "Absolutely. Use the 'Submit an Opportunity' link in the footer. Our team reviews all submissions within 48 hours.",
  },
  {
    q: "Which companies and programs are covered?",
    a: "We cover programs from Google, Microsoft, Amazon, Meta, GitHub, NVIDIA, IBM, Oracle, Cisco, Intel, and hundreds of other companies — plus campus hackathons, government programs, and open source initiatives.",
  },
];
